export const JETTON_MINT_OPCODE = 21;
export const JETTON_INTERNAL_TRANSFER_OPCODE = 0x178d4519;
export const JETTON_CHANGE_ADMIN_OPCODE = 3;
export const JETTON_CHANGE_CONTENT_OPCODE = 4;
export const JETTON_TRANSFER_OPCODE = 0x0f8a7ea5;
export const JETTON_BURN_OPCODE = 0x595f07bc;
export const JETTON_BURN_NOTIFICATION_OPCODE = 0x7bdd97de;
